// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversityEventManagementAPI.Models;

#nullable disable

namespace UniversityEventManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240125043117_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversityEventManagementAPI.Models.Domain.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<Guid>("organizerid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("organizerid");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("UniversityEventManagementAPI.Models.Domain.Person", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("UniversityEventManagementAPI.Models.Domain.Event", b =>
                {
                    b.HasOne("UniversityEventManagementAPI.Models.Domain.Person", "organizer")
                        .WithMany()
                        .HasForeignKey("organizerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organizer");
                });
#pragma warning restore 612, 618
        }
    }
}
